/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Reaction simulation route: predict products, balance deterministically, and
 * generate a student-facing analysis report.
 */

import { Router } from "express";
import {
  balanceEquation,
  verifyBalance,
  molarMass,
  parseFormula,
  classifyReaction,
  estimateEnergetics,
  lookupKnownReaction,
  predictProducts,
  formatEquation,
  ReactionType,
} from "../../src/lib/reactionEngine.js";
import { isInputSafe } from "../safety.js";

const router = Router();

/** Build a Markdown analysis report describing the reaction for a chemistry student. */
function buildReactionReport(params: {
  equation: string;
  balanced: boolean;
  balanceReason?: string;
  type: string;
  observations: string;
  conditions?: string;
  mechanism?: string;
  hazards?: string;
  energetics: { character: string; estimatedDeltaH: number; note: string };
  species: Array<{ formula: string; role: string; coefficient: number; molarMass: number | null }>;
  reactionOccurs: boolean;
  reason?: string;
}): string {
  const {
    equation, balanced, balanceReason, type, observations, conditions,
    mechanism, hazards, energetics, species, reactionOccurs, reason,
  } = params;

  if (!reactionOccurs) {
    return `## Reaction Prediction
**No reaction is predicted** between the specified reactants under the given conditions.

${reason || "Not all combinations of chemicals react. This may be because the species are chemically inert toward one another, both are stable at these conditions, or a driving force (formation of a gas, precipitate, water, or a favourable electron transfer) is absent."}

**Suggestion:** try adjusting the conditions (add heat, a catalyst, or change concentration) or pair the reactant with a more reactive partner.`;
  }

  const massLines = species
    .map((s) => `- **${s.coefficient > 1 ? s.coefficient + " × " : ""}${s.formula}** (${s.role}) — ${s.molarMass !== null ? s.molarMass.toFixed(2) + " g/mol" : "n/a"}`)
    .join("\n");

  return `## Balanced Equation
\`${equation}\`
${balanced ? "This equation is **stoichiometrically balanced** — every element is conserved between reactants and products (Law of Conservation of Mass)." : `⚠️ The predicted products could **not** be balanced as written: ${balanceReason || "check the products."} The qualitative analysis below still applies.`}

## Reaction Classification
This is a **${type}** reaction.

## What You Would Observe
${observations}
${conditions ? `\n**Conditions required:** ${conditions}` : ""}

## Energetics
- **Thermal character:** ${energetics.character}
- **Estimated ΔH (heuristic):** ${energetics.estimatedDeltaH} kJ/mol
- ${energetics.note}

## Molecular-Level Explanation
${mechanism || "The reactants rearrange their bonds: old bonds break and new bonds form to yield the products above, driven toward a lower-energy, more stable arrangement."}

## Species & Molar Masses
${massLines}

## Safety Notes
${hazards || "Follow standard laboratory safety: wear goggles and gloves, work in a fume hood where gases are produced, and handle acids, bases, and oxidizers with care."}

---
*Report generated by the deterministic reaction engine. Balancing and molar masses are computed exactly; energetics are educational estimates.*`;
}

router.post("/api/reaction/simulate", async (req, res) => {
  try {
    let { reactants, conditions } = req.body as { reactants: string[] | string; conditions?: string };

    if (typeof reactants === "string") {
      reactants = reactants.split(/[,+]/).map((r) => r.trim()).filter(Boolean);
    }
    if (!Array.isArray(reactants) || reactants.length === 0) {
      return res.status(400).json({ error: "Provide at least one reactant formula (e.g. reactants: ['CH4','O2'])." });
    }
    reactants = reactants.map((r) => String(r).trim()).filter(Boolean).slice(0, 6);
    const conditionStr = (conditions || "").toString().trim();

    // Safety layer — reuse the fail-closed dual-use scanner.
    const safetyRes = isInputSafe(reactants.join(" ") + " " + conditionStr);
    if (!safetyRes.safe) {
      return res.status(403).json({ safety_tripped: true, error: safetyRes.reason });
    }

    // Validate every reactant is a parseable formula of real elements.
    for (const r of reactants) {
      try {
        parseFormula(r);
      } catch (e: any) {
        return res.status(400).json({ error: `Invalid reactant formula "${r}": ${e?.message || "parse error"}. Use formulas like H2O, NaCl, C2H5OH.` });
      }
    }

    // Predict products: curated knowledge base first, then the deterministic engine.
    let products: string[] = [];
    let productStates: string[] = [];
    let reactantStates: string[] = [];
    let type: string = "Unclassified";
    let observations = "";
    let mechanism = "";
    let hazards = "";
    let predictedConditions = conditionStr;
    let reactionOccurs = true;
    let source = "knowledge-base";

    let predictionReason: string | undefined;
    const known = lookupKnownReaction(reactants);
    if (known) {
      products = known.products;
      type = known.type;
      observations = known.observations;
      predictedConditions = conditionStr || known.conditions || "";
      if (known.states) {
        reactantStates = known.states.slice(0, reactants.length);
        productStates = known.states.slice(reactants.length);
      }
    } else {
      const p = predictProducts(reactants, conditionStr);
      source = "deterministic-engine";
      reactionOccurs = p.reactionOccurs;
      products = p.products;
      productStates = p.productStates;
      reactantStates = p.reactantStates;
      type = p.type;
      observations = p.observations;
      mechanism = p.mechanism || "";
      hazards = p.hazards || "";
      predictedConditions = conditionStr || p.conditions || "";
      predictionReason = p.reason;
      products = products.filter((prod) => {
        try {
          parseFormula(prod);
          return true;
        } catch {
          return false;
        }
      });
      if (reactionOccurs && products.length === 0) reactionOccurs = false;
    }

    // Deterministic balancing + verification.
    let balanced = false;
    let coefficients: number[] = [];
    let balanceReason: string | undefined;
    let equation = reactants.join(" + ") + " → ?";

    if (reactionOccurs && products.length > 0) {
      const result = balanceEquation(reactants, products);
      if (result.balanced && verifyBalance(reactants, products, result.coefficients)) {
        balanced = true;
        coefficients = result.coefficients;
        equation = formatEquation(reactants, products, coefficients);
      } else {
        balanceReason = result.reason;
        coefficients = new Array(reactants.length + products.length).fill(1);
        equation = formatEquation(reactants, products, coefficients);
      }
    }

    if (reactionOccurs && products.length > 0 && (type === "Unclassified" || !type)) {
      type = classifyReaction(reactants, products);
    }

    const energetics = estimateEnergetics(type as ReactionType);

    const allSpecies = [...reactants, ...products];
    const roles = [...reactants.map(() => "reactant"), ...products.map(() => "product")];
    const species = allSpecies.map((formula, i) => {
      let mm: number | null = null;
      try {
        mm = molarMass(formula);
      } catch {
        mm = null;
      }
      return {
        formula,
        role: roles[i],
        state: (i < reactants.length ? reactantStates[i] : productStates[i - reactants.length]) || "",
        coefficient: coefficients.length ? coefficients[i] : 1,
        molarMass: mm,
      };
    });

    const report = buildReactionReport({
      equation, balanced, balanceReason, type, observations,
      conditions: predictedConditions, mechanism, hazards, energetics,
      species, reactionOccurs, reason: predictionReason,
    });

    return res.json({
      reaction_occurs: reactionOccurs,
      reactants,
      products,
      balanced,
      balance_reason: balanceReason,
      reason: predictionReason,
      coefficients,
      equation,
      reaction_type: type,
      observations,
      conditions: predictedConditions,
      mechanism,
      hazards,
      energetics,
      species,
      report,
      source,
    });
  } catch (err: any) {
    console.error("Reaction simulation failure:", err);
    return res.status(500).json({ error: err.message || "An error occurred inside the reaction simulator." });
  }
});

export default router;
